In [4]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pickle
import requests
import json

In [5]:
#importing dataset
dataset=pd.read_csv('D:/datasets/heart.csv')
X = dataset.iloc[:,0:13].values
y = dataset.iloc[:,-1].values

In [6]:
#Splitting dataset into training set and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
# Dimensionality Reduction
# Applying LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components = 2)
X_train = lda.fit_transform(X_train,y_train)
X_test = lda.fit_transform(X_test,y_test)
X_train

C:\Users\Syed\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(1, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
C:\Users\Syed\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_components > min(n_features, n_classes - 1) will raise a ValueError. You should set n_components to None (default), or a value smaller or equal to min(n_features, n_classes - 1).
  warnings.warn(future_msg, FutureWarning)
C:\Users\Syed\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:466: ChangedBehaviorWarning: n_components cannot be larger than min(n_features, n_classes - 1). Using min(n_features, n_classes - 1) = min(1, 2 - 1) = 1 components.
  ChangedBehaviorWarning)
C:\Users\Syed\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:472: FutureWarning: In version 0.23, setting n_co

array([[ 2.28011405],
       [ 1.29304306],
       [ 1.12713495],
       [ 0.45231235],
       [ 0.28104698],
       [ 0.63916824],
       [-0.81006589],
       [ 0.48696886],
       [ 0.04366996],
       [-0.14953291],
       [ 1.5049131 ],
       [ 0.84960769],
       [-1.81132694],
       [-1.51403343],
       [ 0.99669867],
       [-0.71278735],
       [ 0.18157756],
       [ 0.43479033],
       [-0.56806004],
       [-2.62752948],
       [-2.20255228],
       [-1.21891673],
       [-0.28413088],
       [-1.55266416],
       [-0.04791851],
       [-1.8303197 ],
       [ 0.30559855],
       [ 0.47568052],
       [-0.90596443],
       [-1.7289081 ],
       [ 0.48302242],
       [ 0.30645275],
       [-1.82322632],
       [ 1.42009274],
       [-1.85343048],
       [-1.60408934],
       [-2.085508  ],
       [ 1.57858834],
       [-1.66249246],
       [-1.5990848 ],
       [ 2.25028304],
       [-2.50199764],
       [ 0.15023526],
       [-0.95577282],
       [ 1.01709404],
       [ 1

In [8]:
#Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
accuracy_score(y_test,y_pred)
cm4=confusion_matrix(y_test,y_pred)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [9]:
# dumping byte stream of trained object to model_heart.pkl
pickle.dump(gnb, open('model_heart.pkl','wb'))

In [10]:
# loading model into code
model = pickle.load(open('model_heart.pkl', 'rb'))
pred=model.predict(X_test)
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [11]:
precision=cm4[1][1]/(cm4[1][1]+cm4[0][1])
precision

0.9393939393939394

In [12]:
recall=cm4[1][1]/(cm4[1][1]+cm4[1][0])
recall

0.9117647058823529

In [13]:
f1=2*precision*recall/(precision+recall)
f1

0.9253731343283583